In [1]:
import niimpy
from niimpy.preprocessing import location
from niimpy.analysis import social_signature
import pandas
import folium

In [2]:
data = niimpy.reading.google_takeout.location_history(
    "takeout-20241111T082655Z-001.zip",
    start_date = pandas.to_datetime("2022-01-01", utc=True),
    end_date = pandas.to_datetime("2022-06-30", utc=True),
)
data = niimpy.preprocessing.location.filter_location(
    data,
    remove_disabled=False, remove_network=False, remove_zeros=True
)
data.head(5)

KeyboardInterrupt:

In [ ]:
location.location_significant_place_features(data)

,n_sps,n_top2,n_top5,n_moving,n_rare,max_dist_home,n_static,n_transitions,n_top1,device,user,normalized_entropy,n_top4,n_home,entropy,n_top3
timestamp,,,,,,,,,,,,,,,,
2022-04-30 00:00:00+00:00,3.0,31.0,0.0,31.0,2.0,5353.427305,136.0,5.0,92.0,1832214273,03ae8968-3229-11f0-b8a9-1f7c4541e218,4.330821,2.0,91.0,4.757893,11.0
2022-05-31 00:00:00+00:00,16.0,543.0,74.0,1477.0,19.0,40346.976685,4343.0,81.0,3126.0,1832214273,03ae8968-3229-11f0-b8a9-1f7c4541e218,2.423967,94.0,141.0,6.720663,200.0
2022-06-30 00:00:00+00:00,37.0,302.0,82.0,1992.0,70.0,605332.009054,3172.0,164.0,1770.0,1832214273,03ae8968-3229-11f0-b8a9-1f7c4541e218,2.155481,106.0,170.0,7.783265,136.0

In [ ]:
location.find_home(data["latitude"], data["longitude"], data.index)

(np.float64(60.22989181622235), np.float64(24.77360194254112))

In [ ]:
trip_data = data.loc["2022-05-15 12:10:00":"2022-05-15 15:50:00", ["latitude", "longitude"]]
trip_data = trip_data.resample("5min").mean().dropna()
locations = trip_data[["latitude", "longitude"]].drop_duplicates()
map_center = [locations['latitude'].mean(), locations['longitude'].mean()]
mymap = folium.Map(location=map_center, zoom_start=12)

folium.PolyLine(locations[['latitude', 'longitude']].values, color="blue", weight=2.5, opacity=1).add_to(mymap)

for _, row in locations.iterrows():
    folium.Marker(location=[row['latitude'], row['longitude']]).add_to(mymap)

mymap

In [ ]:
mail_data = niimpy.reading.google_takeout.email_activity(
    "takeout-20241111T082655Z-001.zip",
    start_date = pandas.to_datetime("2022-10-01", utc=True),
)
mail_data

Failed to decode message: decode() argument 'encoding' must be str, not None

,received,from,to,cc,bcc,message_id,in_reply_to,character_count,word_count,message_type,user
timestamp,,,,,,,,,,,
2024-11-09 09:59:28+00:00,2024-11-09 01:59:29-08:00,989,[0],[],[],1423,2444,607,57,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2024-11-04 10:29:41+00:00,2024-11-04 02:29:42-08:00,7,[0],[],[],3857,<NA>,2225,262,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2024-11-01 06:44:12+00:00,2024-10-31 23:44:13-07:00,7,[0],[],[],2847,<NA>,1336,146,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2024-10-31 00:39:39+00:00,2024-10-30 17:39:42-07:00,184,[0],[],[],1753,<NA>,1735,170,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2024-10-29 15:42:27+00:00,2024-10-29 08:42:29-07:00,610,[0],[],[],2009,3247,403,13,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
...,...,...,...,...,...,...,...,...,...,...,...
2023-07-14 01:40:06+00:00,2023-07-13 18:41:11-07:00,911,[1039],[],[],3829,3409,461,73,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2024-08-10 14:20:10+00:00,2024-08-10 07:20:24-07:00,321,"[460, 321]",[],[],1317,2201,6370,891,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2024-07-11 18:00:32+00:00,2024-07-11 11:00:53-07:00,631,[631],[],[],1601,3881,2269,213,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2024-09-06 14:32:10+00:00,2024-09-06 07:33:44-07:00,923,[0],[],[],1909,712,3493,169,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218
2023-06-17 13:16:24+00:00,2023-06-17 06:16:26-07:00,95,[0],[],[],1338,<NA>,3540,209,incoming,307848e4-3229-11f0-b8a9-1f7c4541e218

In [ ]:
signature = social_signature.social_signature(mail_data)
signature.head(10)

contact
184    0.084448
906    0.053930
610    0.035953
394    0.035535
643    0.030518
7      0.025920
98     0.025084
154    0.024247
772    0.024247
8      0.022157
dtype: float64

In [ ]:
signature = social_signature.social_signature(mail_data, include_received=False)
signature.head(10)

contact
41      0.166667
733     0.166667
154     0.083333
930     0.055556
356     0.055556
1057    0.055556
341     0.055556
957     0.055556
299     0.027778
335     0.027778
dtype: float64